import React, { useState } from 'react';
import './App.css';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faRobot, faUser } from '@fortawesome/free-solid-svg-icons'

function App() {
  const [selectedIcons, setSelectedIcons] = useState(Array(5).fill(null));
  const [iconColors, setIconColors] = useState(Array(5).fill('#000'));
  const [showModal, setShowModal] = useState(localStorage.getItem('neverShowModal') !== 'true');
  const [neverShow, setNeverShow] = useState(false);

  const handleIconClick = (cardIndex, icon) => {
    setSelectedIcons(prevIcons => {
      const newIcons = [...prevIcons];
      newIcons[cardIndex] = icon;
      return newIcons;
    });

    setIconColors(prevColors => {
      const newColors = [...prevColors];
      newColors[cardIndex] = icon === 'robot' ? '#3B82F6' : '#c30000';
      return newColors;
    });
  };

  return (
    <div className="App">
      {showModal && (
        <div className="modal">
          <div className="modal-content">
          <h2>Welcome to botornot!</h2>
          <p>
            This website presents a game where you will be given 5 answers to the same prompt. 
            Some, all, or none of these answers were generated by an AI.
          </p>
          <p>
            The goal of this game is to guess which answers were generated by the AI and which were not. 
            To make your guess, click on either the user or robot icon next to each answer.
          </p>
          <p>
            Once you've made your decisions, click the "Submit" button to see how many you got right. 
            Good luck and have fun!
          </p>
          <label>
            <input
              type="radio"
              checked={neverShow}
              onChange={() => setNeverShow(!neverShow)}
              className="checkbox"
            />
            Never show again
          </label>
          <button className="button"  onClick={() => {
            localStorage.setItem('neverShowModal', neverShow);
            setShowModal(false);
          }}>Dismiss</button>
          </div>
        </div>

      )}
      <div className="prompt-text">Enter your prompt here</div>
      <div className="cards-container">
        {[...Array(5)].map((_, i) => (
          <div key={i} className={`card ${selectedIcons[i] === 'robot' ? 'robot' : selectedIcons[i] === 'human' ? 'human' : ''}`}>
            
            <div className="icon-robot"  onClick={() => handleIconClick(i, 'robot')}>
              <FontAwesomeIcon icon={faRobot} color={selectedIcons[i] === 'robot' ? iconColors[i] : '#000'} />
            </div>
            <div className="card-content">
              <p>Your text goes here and can be very long up to 140 characters...</p>
            </div>
            
            <div className="icon-human"  onClick={() => handleIconClick(i, 'human')}>
              <FontAwesomeIcon icon={faUser} color={selectedIcons[i] === 'human' ? iconColors[i] : '#000'}/>
            </div>
          </div>
        ))}
      </div>
      <button className="button">Submit</button>
    </div>
  );
}

export default App;